/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardEventsEventIdRouteImport } from './routes/dashboard/events/$eventId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/leads'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/leads'
    | '/dashboard'
    | '/dashboard/events/$eventId'
    | '/dashboard/events'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/leads'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/$eventId': {
      id: '/dashboard/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/dashboard/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
